[default]
general.chip = "nrf52833_xxAA"
reset.halt_afterwards = false
rtt.enabled = false
gdb.enabled = false

[blinky]
rtt.enabled = true

[roulette]

[rtt]
rtt.enabled = true

[uart]
rtt.enabled = true
