[package]
name = "uart"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.3"
embedded-hal = "0.2.7"
heapless = "0.7.16"
microbit-v2 = "0.13.0"
nb = "1.1.0"
panic-halt = "0.2.0"
